### ISSUE TITLE
Can't download e-ac3(5.1) when MQA is available

### ISSUE THREAD

**Issue by alexfrouart** [Dniel97/RedSea#16]
Hello,

using the default TV session (supporting MQA & E-AC3), when MQA codec (stereo) is available for a given track, it overrides E-AC3 and makes it impossible to download 5.1 content.
Is this a known issue, or is there a way to download e-ac3 content even if Master Quality is available for the track?

**Comment by Dniel97** [comment]
You have to use the right album/track URL for E-AC3, Dolby Atmos has always the higher priority if you enabled `spatial_codecs`. Could you provide the URL?

**Comment by Dniel97** [comment]
No further information provided, closing
