### ISSUE TITLE
[QUESTION] Where can we play AC-4 files ?

### ISSUE THREAD

**Issue by SonMaxime** [Dniel97/RedSea#17]
**Describe the bug**
By using the TV ApiKey, i collect m4a files with E-AC3-JOC and i can play them without problem on VLC but when i download m4a files with AC-4 by using the mobile key i can't use them and after various searches I still have not found any open-souce decoder who supports the codec and I was wondering if it was really possible to play them outside of the Tidal app

**Screenshots**
![image](https://user-images.githubusercontent.com/47661880/147471766-e4cbdeab-b9c9-4bd0-845d-592c4a4134c3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version: 3.10.1 (Microsoft Store edition)

**Comment by Dniel97** [comment]
Currently the only way to play AC-4 files is using a new TV with support for it (Samsung, LG,...) , supported Dolby Atmos compatible smartphones (Samsung, Huawei, ...). The only way to play it on PC is via the [Dolby Reference Player](https://professional.dolby.com/product/media-processing-and-delivery/drp---dolby-reference-player/#gref).

**Comment by SonMaxime** [comment]
> Currently the only way to play AC-4 files is using a new TV with support for it (Samsung, LG,...) , supported Dolby Atmos compatible smartphones (Samsung, Huawei, ...). The only way to play it on PC is via the [Dolby Reference Player](https://professional.dolby.com/product/media-processing-and-delivery/drp---dolby-reference-player/#gref).

Thanks!
