### ISSUE TITLE
"presets" commands

### ISSUE THREAD

**Issue by troullll** [Dniel97/RedSea#22]
how can I write command to search one track in 360 RA ? I can't find it with space before [360] and where I misunderstand,
thanks

**Comment by Dniel97** [comment]
Your question makes no sense. Do you mean the [explore](https://github.com/Dniel97/RedSea#exploring) function which let you "explore" the newest 360RA releases? Do you mean the actual search where you can [search](https://github.com/Dniel97/RedSea#exploring) for title, album and artist (keep in mind that you don't search for "360", you just search for album and title and RedSea will show you the available quality)? Your issue title also makes no sense, what do "[presets](https://github.com/Dniel97/RedSea#exploring)" have to do with the search?

**Comment by troullll** [comment]
no problem with exploring or searching fonctions.
ok, presets don't have to do with search.
How to use the "-p" command ?
for example,  any album in 360 in particular ?

**Comment by Dniel97** [comment]
You can find all available presets under ["config/settings.py"](https://github.com/Dniel97/RedSea/blob/173b695b66e3ef9aa9aa3320680c9c001e7d9aff/config/settings.example.py#L73)  you always will download 360 if you use a 360 album/track link and have a mobile session added. For example try the following 360 link: https://tidal.com/album/166786253

**Comment by troullll** [comment]
with links ok.
could you give me an example of writing presets on the settings.py ? I don't know where or how, thanks
(only 360 or Atmos music needed for me)
