### ISSUE TITLE
Can't download any music

### ISSUE THREAD

**Issue by CrossyAtom46** [Dniel97/RedSea#26]
**Describe the bug**
Can't download because my account region is not from US so we should able to change regions

**To Reproduce**
python redsea.py id 179708892

**Screenshots**
![image](https://github.com/Dniel97/RedSea/assets/82151617/29fd7f21-22bb-44fc-94ad-bb8b59d136dc)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Python version 3.11.4

**Comment by Dniel97** [comment]
That is not possible, use the correct links for your account region.
