### ISSUE TITLE
Getting error Downloading low quality Album

### ISSUE THREAD

**Issue by ink79** [Dniel97/RedSea#5]
Hi I'm trying to download this album https://listen.tidal.com/album/115992133

my settings are 

    # Default settings / only download FLAC_16
    "default": {
        "keep_cover_jpg": True,
        "embed_album_art": True,
        "save_album_json": True,
        "tries": 5,
        "path": path,
        "track_format": "{tracknumber} - {title}",
        "album_format": "{albumartist}/{album} ({date}) {quality}{explicit}",
        "video_folder_format": "{artist} - {title}{date}{quality}",
        "video_file_format": "{title}",
        "convert_to_alac": False,
        "save_credits_txt": True,
        "embed_credits": True,
        "save_lyrics_lrc": True,
        "embed_lyrics": True,
        "lyrics_provider_order": ["Deezer", "musiXmatch"],
        "genre_language": "en-US",
        "artwork_size": 3000,
        "uncompressed_artwork": True,
        "resolution": 1080,
        "MQA_FLAC_24": True,
        "FLAC_16": True,
        "AAC_320": True,
        "AAC_96": True
    },

but getting this error when I try to download

```
Default session is currently set to: xxxxxx

=== 38/53 complete (72% done) ===

=== Downloading track ID 115992172 ===
	Please use a mobile session for the track 115992172 in LOSSLESS audio quality. This cannot be downloaded with a TV session for now.

Choose one of the following mobile sessions: 

SESSIONS:
   [TR][MOBILE] xxx | xxx
	+-----------+----------------------------------------------------------------+-----------+
	| Codec     | Technical name                                                 | Supported |
	+-----------+----------------------------------------------------------------+-----------+
	| eac3      | E-AC-3 JOC (Dolby Digital Plus with Dolby Atmos, with 5.1 bed) | False     |
	| mha1      | MPEG-H 3D Audio (Sony 360 Reality Audio)                       | True      |
	| ac4       | AC-4 IMS (Dolby AC-4 with Dolby Atmos immersive stereo)        | False     |
	| mqa       | MQA (Master Quality Authenticated) in FLAC container           | True      |
	| flac      | FLAC (Free Lossless Audio Codec)                               | False     |
	| alac      | ALAC (Apple Lossless Audio Codec)                              | False     |
	| mp4a.40.2 | AAC 320 (Advanced Audio Coding) with a bitrate of 320kb/s      | False     |
	| mp4a.40.5 | AAC 96 (Advanced Audio Coding) with a bitrate of 96kb/s        | False     |
	+-----------+----------------------------------------------------------------+-----------+
```

reCAPTCHA  did not worked so I added auth code from mobile device

**Comment by Dniel97** [comment]
Congratulations for finding a new bug! Could you also provide the `auth list` for the session `xxxxxx`? I just tried the command `python redsea.py https://tidal.com/browse/track/115992172` and had no issue downloading it with a TV session as a .flac file.

BTW: reCAPTCHA is currently disabled, so if you want to create a new mobile session directly in RedSea you can do that by using the [develop branch](https://github.com/Dniel97/RedSea/tree/develop)

**Comment by ink79** [comment]
session- Narzo
auth list- eyJraWQiOiI4UUhqclVzdSIsImFsZyI6IlJTMjU2In0.eyJ0eXBlIjoibzJfYWNjZXNzIiwidWlkIjoxNzkxMjUxNzAsInNjb3BlIjoid19zdWIgcl91c3Igd191c3IiLCJnVmVyIjowLCJzVmVyIjoxLCJjaWQiOjQ2NTEsImN1ayI6IjJiODE2ODE0MmQ4NTliM2EiLCJleHAiOjE2MjIxNTIzMTIsInNpZCI6IjkxNzVjMTRlLTQ3NmYtNGUzYi1hOTViLWVjMzI0ZjYwMDRkNiIsImlzcyI6Imh0dHBzOi8vYXV0aC50aWRhbC5jb20vdjEifQ.NskmHBOlQPZbuHQFP_AXasQHUiQFx68CLMrY8vf7gM23KGado3U6a_SG5vIROjBFlE_1kUS2AHJkcGNqy-_qCN7-v7o_gBEmbCmxcEJHcnlj-wDwx_QjVTY7SSsAmGWUKgB7LG2aDnz1HoGyKLXM9NIKu4YjbBAAVvX4NremmKCfOT-6R6kyEhAFoItHWFr39xu7K3BkkPNzA9gb2J8CLtOWklloitQwsL-enDtZUOobFt5BVA4zBGwRYzdTMp5AHJoG8AD6P-gmPas6l_SIA5wfD4n-aGuwxhtrgD_KzfUKlBtE-pDcmxxpPTduXCM0J4xlRT1XKmS-tKka3csscQ

**Comment by ink79** [comment]
using the develop branch added a new session not seeing any issue now.

**Comment by Dniel97** [comment]
Perfect, I will close the issue now. If you still have issues feel free to open it again!
