### ISSUE TITLE
continue with apple

### ISSUE THREAD

**Issue by dts350z** [Dniel97/RedSea#7]
Is it possible to sign in (mobile) if you used an apple id for Tidal?

I need mobile for 360 format (if I understand correctly).

**Comment by Dniel97** [comment]
Yes you need the mobile session for Sony 360RA, but there are currently no plans to add support for "Sign in" through Google or Apple. If you aren't familiar with Sony 360RA I'd recommend reading #6 and choose if you really need it.

**Comment by dts350z** [comment]
I was assuming RedSea was going to give some number of channels in flac or other format. Perhaps this was just rumors rather than a built in capability.

In a perfect world you would be able to extract up to 13.2 channels (Sony's setup when creating content, 5 top, 5 mid, 3 Bottom, plus stereo subs: https://www.ecoustics.com/articles/sony-360-reality-audio-tour/) but I don't know if ffmpeg can do that (yet) or not.

Obviously flac is limited to 8 channels, but wav or wavpak can have more.

and yes I can playback (though most people could not) up to 16ch wav files (genelecs, as in the sony studio, or via Smyth Realiser A16 and headphones). 

Some people would also like the multi channels for their re-mixing hobby.

**Comment by Dniel97** [comment]
No, RedSea is just a downloader (and tagger) not a Sony 360RA decoder. Ffmpeg can't decode MPEG-H at all, you need another decoder for it.

Exactly you would need simple WAV or WAVPACK. What is your speaker layout? If you can play 16 WAV files, therefore I think you mean a 16ch WAV file or 16 mono wav files. So I guess you have a 9.1.6 Dolby Atmos layout? Smyth Realiser A16 sounds really nice but I'd prefer real speaker over a HTRF related headphone virtualization. 

I know that many people want Stems from the Sony 360RA mixes, but it also depends on the mix, some only have 4 objects other have 13.

**Comment by dts350z** [comment]
My speaker layout in the studio is 7.2.4 (plus one more straight overhead
for Auro 3D), all genelecs, however I almost never turn them on since
getting the Realiser 16.

With calibrated SENNHEISER HD 800 S, or other good headphones you literally
can't tell the difference. Other than the physical touch of the headphones
on your head you'd swear the speakers were on and not the headphones. The
only difference is the Realiser doesn't have 6DOF (sources don't get louder
or softer as  you move closer or farther away).

The Realiser can be configured for any layout, up to 16 channels.

Re ffmpeg and Mpeg-h decoding I had seen some notes on line where 360
decoding looked like it was being added:

Can't find it in my browser history at the moment but there were
screenshots of the comments where they were adding the 13.2 channel layout
specifically for Sony 360 RA.

I guess this:
http://ffmpeg.org/pipermail/ffmpeg-devel/2019-October/251743.html

just addresses demuxing (vs. decoding).

There is this "reference software" decoder source:
https://www.mpegstandards.org/standards/MPEG-H/6/

-Glenn

**Comment by Dniel97** [comment]
No plans to integrate "Continue with ..." at the moment.
